name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - ""
          - --disable-curses
          - --disable-lua
          - --disable-tre
          - --disable-help
    env:
      CFLAGS_EXTRA: --coverage
      LDFLAGS_EXTRA: --coverage
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependency Homebrew
      run: |
        brew install \
          coreutils \
          libtermkey \
          lua \
          luarocks \
          tre \
          pkg-config

    - name: Dependency LuaRocks
      run: |
        sudo luarocks install lpeg

    - name: Build
      run: |
        ./configure ${{ matrix.config }}
        make

    - name: Test
      run: |
        make test

    - name: Upload Test Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -s https://codecov.io/bash > codecov
        curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/SHA256SUM > codecov.sha256
        if sha256sum -c --ignore-missing --status codecov.sha256 ; then
          bash < codecov || true
        else
          echo "Download checksum verification failed"
        fi
